# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License. 

jobs:
- job: IMAGES_BUILD
  timeoutInMinutes: 420
  pool:
    vmImage: ubuntu-latest

  steps:
  - bash: |
        mkdir -p $(Build.ArtifactStagingDirectory)/bfbs
        pwd
        ls $(System.DefaultWorkingDirectory)
    displayName: 'Prep Workspace'

  - script: |
      set -x
      docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      sudo $(System.DefaultWorkingDirectory)/bfb-build
      cp *.bfb '$(Build.ArtifactStagingDirectory)/bfbs/'
    displayName: 'Run bfb-build'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish bfb'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/bfbs/'
      artifact: 'bfb'
